#!/bin/sh
#echo "Jahr: " $1
#echo "Name: " $2
#echo "Bild: " $3

#echo "create labels"
convert -gravity center -font URW-Palladio-L-Bold -pointsize 36 label:"$1" _jahr.png
convert -gravity center -font URW-Palladio-L-Bold -pointsize 32 -size x40 -interline-spacing -10 label:"$2" _name.png #fruher stand da -size x61
convert -resize 320x500 -bordercolor gray33 -border 1 "$3" _bild.jpg

#echo "merge components"
composite -gravity center -geometry +0-294 _jahr.png vorlageOhneBild.png t1.png
composite -gravity center -geometry +0+308 _name.png t1.png t2.png
composite -gravity center -colorspace sRGB _bild.jpg t2.png "$1".jpg

#remove temporary files
rm _jahr.png
rm _name.png
rm _bild.jpg
rm t?.png
